version: '3'
services:
  db:
    image: mysql:5.7.21
    volumes:
      - db_data:/var/lib/mysql
      - "./docker/sql-init:/docker-entrypoint-initdb.d"
      - "./docker/script-db:/docker-script-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: test
      MYSQL_USER: clem
      MYSQL_PASSWORD: azerty
    ports:
      - 127.0.0.1:3306:3306
volumes:
  db_data: